ERROR:root:An error occurred in file 'utils_api.py', line 688: 'Total_Profit_By_Active'
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/SPOT_MARKET_ASSISTENT/API_BINANCE/utils_api.py", line 679, in get_myBook
    total_total_profit = sum(float(x['Total_Profit_By_Active']) for x in formatted_trades_list if x['Total_Profit_By_Active'] and x['Total_Profit_By_Active'] != ' ')
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/SPOT_MARKET_ASSISTENT/API_BINANCE/utils_api.py", line 679, in <genexpr>
    total_total_profit = sum(float(x['Total_Profit_By_Active']) for x in formatted_trades_list if x['Total_Profit_By_Active'] and x['Total_Profit_By_Active'] != ' ')
                                                                                                  ~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Total_Profit_By_Active'
ERROR:root:An error occurred in file 'utils_api.py', line 688: 'Total_Profit_By_Active'
Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/SPOT_MARKET_ASSISTENT/API_BINANCE/utils_api.py", line 539, in csv_write_trades
    total_profit = round(float(trade['Total_Profit_By_Active']), 3)
                             ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Total_Profit_By_Active'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/SPOT_MARKET_ASSISTENT/API_BINANCE/utils_api.py", line 684, in get_myBook
    self.csv_write_trades(formatted_trades_list, label, cur_time, total_total_profit)
  File "/home/kali/Desktop/ALL_PROJECT/TREADING/SPOT_MARKET_ASSISTENT/API_BINANCE/utils_api.py", line 541, in csv_write_trades
    total_profit = trade['Total_Profit_By_Active']
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Total_Profit_By_Active'
